# SPDX-FileCopyrightText: 2025 ICRC
#
# SPDX-License-Identifier: BSD-3-Clause

FROM openmrs/openmrs-reference-application-3-frontend:qa


#To activate oauth2 authentication.
COPY oauth2.json /usr/share/nginx/html/oauth2.json
