version: "3.7"

services:

  frontend:
    build:
      context: frontend

  backend:
    build:
      context: backend

  # MariaDB
  database:
    build:
      context: database

  keycloak:
    build:
      context: keycloak