# SPDX-FileCopyrightText: 2025 ICRC
#
# SPDX-License-Identifier: BSD-3-Clause

FROM openmrs/openmrs-reference-application-3-gateway:qa

ENV FRAME_ANCESTORS ""
ENV GATEWAY_PORT 8080
COPY default.conf.template /etc/nginx/templates/
