name: Publish MariaDB docker image with openmrs dump

on:
  workflow_dispatch:
# See https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mariadb-10
  IMAGE_TAG: 2.5.12
jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./database
          push: true
#          tags: "${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          tags: "${{ env.IMAGE_NAME }}:main"
          labels: ${{ steps.meta.outputs.labels }}
