# SPDX-FileCopyrightText: 2025 ICRC
#
# SPDX-License-Identifier: BSD-3-Clause

name: Publish Keycloak docker image with automatic users creation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - keycloak/**
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: keycloak
  IMAGE_VERSION: 24.0.3
  IMAGE_TAG: latest
  CONTEXT: ./keycloak
jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.IMAGE_VERSION }}-${{ env.IMAGE_TAG }}
            type=sha,prefix=${{ env.IMAGE_VERSION }}-

      - name: Build and push Keycloak Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.CONTEXT }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
