name: Publish MariaDB For OpenMRS 2.6.4 docker image

on:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mariadb-10-openmrs
  IMAGE_VERSION: 2.6.4
  IMAGE_TAG: latest
  CONTEXT: ./database
jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.IMAGE_VERSION }}-${{ env.IMAGE_TAG }}
            type=sha,prefix=${{ env.IMAGE_VERSION }}-

      - name: Build and push MariaDB Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.CONTEXT }}
          build-args: |
            DUMP_FILENAME=openmrs-2.6.4.sql.gz

          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
