name: Publish OpenMRS Backend docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - include-extension
    paths:
      - backend/**
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: openmrs-backend
  IMAGE_VERSION: 2.5.13
  IMAGE_TAG: latest
  CONTEXT: ./backend
jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: 11
          overwrite-settings: true
          server-id: openmrs-module-fhir2extension
          settings-path:

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.IMAGE_VERSION }}-${{ env.IMAGE_TAG }}
            type=sha,prefix=${{ env.IMAGE_VERSION }}-

      - name: Display M2 settings
        run: cat ~/.m2/settings.xml

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            "m2settings=<settings>
              <servers>
                <server>
                  <id>openmrs-module-fhir2extension</id>
                  <username>${env.GITHUB_ACTOR}</username>
                  <password>${env.GITHUB_TOKEN}</password>
              </server>
            </servers></settings>"
#          secret-files: |
#            "m2settings=~/.m2/settings.xml"
